package:
  name: kapteyn
  version: "2.3"

source:
  fn: kapteyn-2.3.tar.gz
  url: https://files.pythonhosted.org/packages/0a/c3/4ceffdeb87918ade3dc9649e100d3b0be0fdc38b5105324b17686a3e0e48/kapteyn-2.3.tar.gz
  md5: 9abb373995d1b683936c48485a41c2b4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - kapteyn = kapteyn:main
    #
    # Would create an entry point called kapteyn that calls kapteyn.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy
    - cython
  run:
    - python
    - numpy
    - six
test:
  # Python imports
  imports:
    - kapteyn
    - kapteyn.wcs
  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.astro.rug.nl/software/kapteyn/
  license: BSD License or GNU Library or Lesser General Public License (LGPL)
  summary: 'Kapteyn Package: Python modules for astronomical applications'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
