package:
  name: jprops
  version: "1.0"

source:
  fn: jprops-1.0.tar.gz
  url: https://files.pythonhosted.org/packages/1f/57/42e0088e3607b2d157bb039ba5c19536010f3d505871573cb28020e1e1d6/jprops-1.0.tar.gz
  md5: d150084738d03d8046418a0f79879821
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - jprops = jprops:main
    #
    # Would create an entry point called jprops that calls jprops.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mgood.github.com/jprops/
  license: BSD
  summary: 'Parser for Java .properties files'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
