package:
  name: layeredconfig
  version: "0.1.0"

source:
  fn: layeredconfig-0.1.0.tar.gz
  url: https://files.pythonhosted.org/packages/d8/a3/9818f77bda2e9c1a490f353d6f9bd5a1d301e20c7b7172600b0a69829291/layeredconfig-0.1.0.tar.gz
  md5: c19b10f505fa39f4656ac64072c5619d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - layeredconfig = layeredconfig:main
    #
    # Would create an entry point called layeredconfig that calls layeredconfig.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six
    - pyyaml

  run:
    - python
    - six
    - pyyaml
    - requests
test:
  # Python imports
  imports:
    - layeredconfig

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/staffanm/layeredconfig
  license: BSD License
  summary: 'Manages configuration coming from config files, environment variables, command line arguments, code defaults or other sources'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
